services:

  backend:
    build: ./backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    depends_on:
      - postgres

  postgres:

    image: postgres:17

    restart: always

    environment:
      POSTGRES_DB: obabueki

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:

  postgres_data: