"""add description to portfolios

Revision ID: f2584d335a35
Revises: 2bc869740f7a
Create Date: 2026-07-15 00:28:45.165051

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f2584d335a35"
down_revision: Union[str, Sequence[str], None] = "2bc869740f7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "portfolios", sa.Column("description", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("portfolios", "description")
    # ### end Alembic commands ###
